name: Build and release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build
      env:
          ARCH: ${{
            runner.arch == 'X86' && 'x86' ||
            runner.arch == 'X64' && 'amd64' ||
            runner.arch == 'ARM' && 'arm' ||
            runner.arch == 'ARM64' && 'arm64' ||
            runner.arch }}
          OS: ${{
            runner.os == 'Linux' && 'linux' ||
            runner.os == 'Windows' && 'window' ||
            runner.os == 'macOS' && 'macos' ||
            runner.os }}
      run: |
        export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
        go build -ldflags "-X main.version=${GITHUB_REF_NAME#v}" -v ./cmd/...
        mv readknead readknead-${{ env.OS }}-${{ env.ARCH }}
        ls -l
        # Save version
        echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

    - name: Test
      run: go test -v ./...

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        name: "ReadKnead ${{ env.RELEASE_VERSION }}"
        artifacts: "readknead*"
